#!/bin/bash
###############################################################################
#
# enable_project
#
USAGE="$0 [-t target_obs] project"
#
# Eg: enable_project OpenHPC:1.3:Factory
#
# Enable all build targets for every package in the given project
#
###############################################################################

TARGET=https://localhost
while getopts t: line
do
  case $line in
  t) TARGET=$OPTARG;;
  *) echo $USAGE; exit 2;;
  esac
done
shift $(($OPTIND - 1))

if [[ $# -ne 1 ]]
then
  echo $USAGE
  exit 2
fi
PROJECT=$1

PACKAGES="$(osc -A $TARGET ls $PROJECT)"

for PACKAGE in $PACKAGES
do
  echo "$PROJECT : $PACKAGE"
  osc -A $TARGET api -X POST "/source/$PROJECT/$PACKAGE?cmd=remove_flag&flag=build&status=enable&arch=aarch64"
  osc -A $TARGET api -X POST "/source/$PROJECT/$PACKAGE?cmd=remove_flag&flag=build&status=enable&arch=x86_64"
  osc -A $TARGET api -X POST "/source/$PROJECT/$PACKAGE?cmd=remove_flag&flag=build"
done
osc -A $TARGET api -X POST "/source/$PROJECT?cmd=remove_flag&flag=build"
