#!/bin/bash
###############################################################################
#
# remove_constraints
#
USAGE="$0 [-t target_obs] project"
#
# Eg: remove_constraints OpenHPC:1.3:Factory
#
# Remove all the contrainsts for every package in the given project
#
###############################################################################

TARGET=https://localhost
while getopts t: line
do
  case $line in
  t) TARGET=$OPTARG;;
  *) echo $USAGE; exit 2;;
  esac
done
shift $(($OPTIND - 1))

if [[ $# -ne 1 ]]
then
  echo $USAGE
  exit 2
fi
PROJECT=$1

PACKAGES="$(osc -A $TARGET ls $PROJECT)"

for PACKAGE in $PACKAGES
do
  echo "$PROJECT : $PACKAGE"
  osc -A $TARGET api -X GET "/source/$PROJECT/$PACKAGE/_constraints" 2>/dev/null
  if [ $? -eq 0 ]
  then
    osc -A $TARGET api -X DELETE "/source/$PROJECT/$PACKAGE/_constraints"
  fi
done
